name: "Go Checks"
description: 'Common golang checks for imoore76 go projects'
inputs:
  version:
    description: 'Version of go-task to use'
    required: false
    default: 'latest'
  tasks:
    description: "Tasks to run, separated by spaces"
    required: false
    default: 'check'
outputs:
  output:
    description: "Task output"
    value: ${{ steps.task-run.outputs.output}}
runs:
  using: "composite"
  steps:
    - run: sudo apt-get install pcre2-utils
      shell: bash
    - run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -b ~/.local/bin -d "${{ inputs.version }}"
      shell: bash
    - run: go install github.com/gordonklaus/ineffassign@latest
      shell: bash
    - run: go install honnef.co/go/tools/cmd/staticcheck@latest
      shell: bash
    - run: go install github.com/client9/misspell/cmd/misspell@latest
      shell: bash
    - run: go install github.com/fzipp/gocyclo/cmd/gocyclo@latest
      shell: bash
    - run: go install github.com/google/addlicense@latest
      shell: bash
    - name: "Run tasks"
      id: task-run
      run: ~/.local/bin/task ${{ inputs.tasks }}
      shell: bash
branding:
  icon: 'zap'
  color: 'blue'
